### ISSUE TITLE
temporary boot supported?

### ISSUE THREAD

**Issue by Anonymous1808-tech** [Xiaomi-fire-unofficial-development/twrp_device_xiaomi_fire#12]
Hey i'm again is temporary boot supported?

**Comment by AntarcticShaurant** [comment]
Hello, 
No, temporary boot isn't supported, but as i said, it's not TWRP's fault, but the device's.

**Comment by Anonymous1808-tech** [comment]
> Hello, 
> No, temporary boot isn't supported, but as i said, it's not TWRP's fault, but the device's.

Can you Tell me the Recovery Partition Name for fastboot flash?

**Comment by Anonymous1808-tech** [comment]
> > Hello, 
> > No, temporary boot isn't supported, but as i said, it's not TWRP's fault, but the device's.
> 
> Can you Tell me the Recovery Partition Name for fastboot flash? 

No recovery Partition found and with fastboot flash recovery_ab too

**Comment by Anonymous1808-tech** [comment]
How did you flash it? Which Methode?

**Comment by AntarcticShaurant** [comment]
You'll find a guide in the releases page, I'm adding it right now.

**Comment by AntarcticShaurant** [comment]
Alright, done!

**Comment by Anonymous1808-tech** [comment]
> Alright, done!

Guide is Not showing Up or i'm to dumb
