### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Anonymous1808-tech** [Xiaomi-fire-unofficial-development/twrp_device_xiaomi_fire#13]
I've tried your twrp now, it works but I found a few errors. The battery bar sometimes goes crazy and only shows 1% when you flash something via the TWRP, it doesn't matter whether the option is on or not, it is on A and B. The cell phone cannot be switched off using the power function in the TWRP. ADB has sideload Doesn't work, error keeps coming, I have to test it again myself to see what the problem is. To reproduce the Bug do fastboot flash twrp and try to go to reboot section Power Off. For the battery,Its a random Thing.

**Comment by AntarcticShaurant** [comment]
Hmm, it never happened before.
Could you share some logs of the error? you'll find the option in Advanced > Copy Log > and include both logcat and kernel log.

Thank you!

**Comment by AntarcticShaurant** [comment]
Also, what did you try to flash?

**Comment by ghost** [comment]
![Screenshot from 2024-03-04 23-31-08](https://github.com/redmi-fire-devs/twrp_device_xiaomi_fire/assets/138833621/90541c57-a00e-4609-a138-08c905ed7929)
uhhh thats weird... adb sideload works fine for me.

**Comment by Anonymous1808-tech** [comment]
> ![Screenshot from 2024-03-04 23-31-08](https://private-user-images.githubusercontent.com/138833621/309907443-90541c57-a00e-4609-a138-08c905ed7929.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDE0MzcsIm5iZiI6MTcwOTY0MTEzNywicGF0aCI6Ii8xMzg4MzM2MjEvMzA5OTA3NDQzLTkwNTQxYzU3LWEwMGUtNDYwOS1hMTM4LTA4YzkwNWVkNzkyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMjE4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDRiOGJjMTg0NTk2Njg3NzJmODExNDE2OTc1NGMxMmZlN2ZiYzUzMjY4NTIxYzljMzMzNjljNzE0MDllNmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DDAf3o_HiL54YAPW5Za3tlKuxnjgEU6unryy_CfDE-0) uhhh thats weird... adb sideload works fine for me.

Maybe i did Something wrong i will try at again

**Comment by Anonymous1808-tech** [comment]
> Also, what did you try to flash?

Custom rom

**Comment by Anonymous1808-tech** [comment]
> Hmm, it never happened before. Could you share some logs of the error? you'll find the option in Advanced > Copy Log > and include both logcat and kernel log.
> 
> Thank you!

Sry i reversed every thing what i did,i try to recreate it today. I will Safe for the Future all log's

**Comment by AntarcticShaurant** [comment]
> > Also, what did you try to flash?
> 
> Custom rom

Did you mean a GSI?

**Comment by AntarcticShaurant** [comment]
> > Hmm, it never happened before. Could you share some logs of the error? you'll find the option in Advanced > Copy Log > and include both logcat and kernel log.
> > Thank you!
> 
> Sry i reversed every thing what i did,i try to recreate it today. I will Safe for the Future all log's

No problem and thank you

**Comment by AntarcticShaurant** [comment]
Well, i guess I'll close this issue for inactivity.

Feel free to reopen it though.
