### ISSUE TITLE
Touchscreen not working: Failed to load firmware focaltech_8725_fw.bin

### ISSUE THREAD

**Issue by skvorecoo** [Xiaomi-fire-unofficial-development/twrp_device_xiaomi_fire#14]
The touch screen does not work in recovery. The logs show that the firmware file could not be found: 
 `(0)[137:kworker/u16:1]fts_ts spi2.0: Direct firmware download for focustech_8725_fw.bin failed with error -2`
I solved the problem by adding focustech_8725_2_fw.bin, focus_ft8725_2_hx.ini files to the vendor/firmware. Now the touchscreen works

**Comment by AntarcticShaurant** [comment]
Ah thanks for reporting!

May i ask where did you find the missing firmware? I couldn't find it anywhere.

**Comment by ghost** [comment]
> where did you find the missing firmware? I couldn't find it anywhere.

in the stock rom?
/vendor/firmware/focaltech_8725_2_fw.bin
/vendor/firmware/focaltech_ft8725_2_hx.ini
&
/vendor/firmware/focaltech_8725_fw.bin
/vendor/firmware/focaltech_ft8725_hx.ini

**Comment by ghost** [comment]
![1711215730_grim](https://github.com/redmi-fire-devs/twrp_device_xiaomi_fire/assets/164667393/3656638e-143b-4ed1-951e-0a8509c1ec05)
your dt has drivers only for focaltech 8720, whilst there is also 8725

**Comment by AntarcticShaurant** [comment]
> > where did you find the missing firmware? I couldn't find it anywhere.
> 
> in the stock rom? /vendor/firmware/focaltech_8725_2_fw.bin /vendor/firmware/focaltech_ft8725_2_hx.ini & /vendor/firmware/focaltech_8725_fw.bin /vendor/firmware/focaltech_ft8725_hx.ini

Ah alright, thank you.

Since the log said focustech and not focaltech i guess i misunderstood

**Comment by ghost** [comment]
I think you can close the issue.

**Comment by AntarcticShaurant** [comment]
Wanted to wait until the next build, but alright.

Feel free to reopen it if the error persists.

**Comment by skvorecoo** [comment]
Thank you. Sorry for the mistake, I don't know why I wrote focustech instead of focaltech

**Comment by RhythmConnoisseurYT** [comment]
Hello,
I know this issue has just been closed and I see the commit but I'm still dealing with non-responsiveness from this. I even attempted wiping the phone with "fastboot -w" and reflashing this TWRP but still no touch.
I have the model 23053RN02L 256gb/8gb for reference if that helps.

**Comment by skvorecoo** [comment]
The author has not yet compiled the new version. If you want, you can use this for now
https://drive.google.com/file/d/1wvITSYeiNf9cBc6oUM8y9izBbS0MdEtE/view?usp=sharing

**Comment by skvorecoo** [comment]
> Hello, I know this issue has just been closed and I see the commit but I'm still dealing with non-responsiveness from this. I even attempted wiping the phone with "fastboot -w" and reflashing this TWRP but still no touch. I have the model 23053RN02L 256gb/8gb for reference if that helps.

The author has not yet compiled the new version. If you want, you can use this for now
https://drive.google.com/file/d/1wvITSYeiNf9cBc6oUM8y9izBbS0MdEtE/view?usp=sharing

**Comment by skvorecoo** [comment]
> Hello, I know this issue has just been closed and I see the commit but I'm still dealing with non-responsiveness from this. I even attempted wiping the phone with "fastboot -w" and reflashing this TWRP but still no touch. I have the model 23053RN02L 256gb/8gb for reference if that helps.

The author has not yet compiled the new version. If you want you can try my version
https://drive.google.com/file/d/1wvITSYeiNf9cBc6oUM8y9izBbS0MdEtE/view?usp=sharing

**Comment by RhythmConnoisseurYT** [comment]
> > Hello, I know this issue has just been closed and I see the commit but I'm still dealing with non-responsiveness from this. I even attempted wiping the phone with "fastboot -w" and reflashing this TWRP but still no touch. I have the model 23053RN02L 256gb/8gb for reference if that helps.
> 
> The author has not yet compiled the new version. If you want you can try my version https://drive.google.com/file/d/1wvITSYeiNf9cBc6oUM8y9izBbS0MdEtE/view?usp=sharing

Ah my apologies. I'm new to Github so I thought a commit was a term for a change already made. 

Thanks for the link. Access is restricted though. Should I request access or will you open it?

**Comment by skvorecoo** [comment]
> > > Hello, I know this issue has just been closed and I see the commit but I'm still dealing with non-responsiveness from this. I even attempted wiping the phone with "fastboot -w" and reflashing this TWRP but still no touch. I have the model 23053RN02L 256gb/8gb for reference if that helps.
> > 
> > 
> > The author has not yet compiled the new version. If you want you can try my version https://drive.google.com/file/d/1wvITSYeiNf9cBc6oUM8y9izBbS0MdEtE/view?usp=sharing
> 
> Ah my apologies. I'm new to Github so I thought a commit was a term for a change already made.
> 
> Thanks for the link. Access is restricted though. Should I request access or will you open it?

opened access

**Comment by RhythmConnoisseurYT** [comment]
> > > > Hello, I know this issue has just been closed and I see the commit but I'm still dealing with non-responsiveness from this. I even attempted wiping the phone with "fastboot -w" and reflashing this TWRP but still no touch. I have the model 23053RN02L 256gb/8gb for reference if that helps.
> > > 
> > > 
> > > The author has not yet compiled the new version. If you want you can try my version https://drive.google.com/file/d/1wvITSYeiNf9cBc6oUM8y9izBbS0MdEtE/view?usp=sharing
> > 
> > 
> > Ah my apologies. I'm new to Github so I thought a commit was a term for a change already made.
> > Thanks for the link. Access is restricted though. Should I request access or will you open it?
> 
> opened access

Ugh. Wiped, reflashed and OrangeFox booted but no touch still :/ I wonder why, but thanks for trying though.

**Comment by skvorecoo** [comment]
> > > > > Hello, I know this issue has just been closed and I see the commit but I'm still dealing with non-responsiveness from this. I even attempted wiping the phone with "fastboot -w" and reflashing this TWRP but still no touch. I have the model 23053RN02L 256gb/8gb for reference if that helps.
> > > > 
> > > > 
> > > > The author has not yet compiled the new version. If you want you can try my version https://drive.google.com/file/d/1wvITSYeiNf9cBc6oUM8y9izBbS0MdEtE/view?usp=sharing
> > > 
> > > 
> > > Ah my apologies. I'm new to Github so I thought a commit was a term for a change already made.
> > > Thanks for the link. Access is restricted though. Should I request access or will you open it?
> > 
> > 
> > opened access
> 
> Ugh. Wiped, reflashed and OrangeFox booted but no touch still :/ I wonder why, but thanks for trying though.

try boot to recovery and type in terminal 
`adb shell dmesg | grep error`

**Comment by RhythmConnoisseurYT** [comment]
> > > > > > Hello, I know this issue has just been closed and I see the commit but I'm still dealing with non-responsiveness from this. I even attempted wiping the phone with "fastboot -w" and reflashing this TWRP but still no touch. I have the model 23053RN02L 256gb/8gb for reference if that helps.
> > > > > 
> > > > > 
> > > > > The author has not yet compiled the new version. If you want you can try my version https://drive.google.com/file/d/1wvITSYeiNf9cBc6oUM8y9izBbS0MdEtE/view?usp=sharing
> > > > 
> > > > 
> > > > Ah my apologies. I'm new to Github so I thought a commit was a term for a change already made.
> > > > Thanks for the link. Access is restricted though. Should I request access or will you open it?
> > > 
> > > 
> > > opened access
> > 
> > 
> > Ugh. Wiped, reflashed and OrangeFox booted but no touch still :/ I wonder why, but thanks for trying though.
> 
> try boot to recovery and type in terminal `adb shell dmesg | grep error`

I'm not sure how to access the original recovery on this phone. When I tried flashing to it, I got the message that the partition doesn't exist and when I typed in [fastboot reboot recovery], it just booted into OrangeFox.

**Comment by skvorecoo** [comment]
write this when you boot into orangefox or twrp

**Comment by RhythmConnoisseurYT** [comment]
Oh okay. I'm used to adb sideload so I didn't know you could access adb from the base. Anyways, the terminal didn't recognize grep error but when I just did adb shell dmesg, I found similar errors to the ones you previously found in the OP 

[   28.602633] (6)[661:ueventd]ueventd: firmware: could not find firmware for focaltech_8725_fw.bin
[   28.602653] (6)[661:ueventd]ueventd: firmware: attempted /etc/firmware/focaltech_8725_fw.bin, open failed: No such file or directory
[   28.602669] (6)[661:ueventd]ueventd: firmware: attempted /odm/firmware/focaltech_8725_fw.bin, open failed: No such file or directory
[   28.602686] (6)[661:ueventd]ueventd: firmware: attempted /vendor/firmware/focaltech_8725_fw.bin, open failed: No such file or directory
[   28.602701] (6)[661:ueventd]ueventd: firmware: attempted /firmware/image/focaltech_8725_fw.bin, open failed: No such file or directory
[   28.602771] (6)[661:ueventd]ueventd: loading /devices/platform/11012000.spi2/spi_master/spi2/spi2.0/firmware/focaltech_8725_fw.bin took 0ms
[   28.603152] (2)[309:irq/135-fts_ts][FTS_TS/E]fts_fw_resume:fts_fw_resume:firmware(focaltech_8725_fw.bin) request fail,ret=-11\x0a

**Comment by AntarcticShaurant** [comment]
Alright, I'll reopen the issue, and keep it open until this gets fixed.

I'm making a test build right now, which I will attach on this comment.

Bear in mind that this won't be a production build, since i still have to fix other things.

**Comment by ghost** [comment]
> Oh okay. I'm used to adb sideload so I didn't know you could access adb from the base. Anyways, the terminal didn't recognize grep error but when I just did adb shell dmesg, I found similar errors to the ones you previously found in the OP
> 
> [ 28.602633] (6)[661:ueventd]ueventd: firmware: could not find firmware for focaltech_8725_fw.bin [ 28.602653] (6)[661:ueventd]ueventd: firmware: attempted /etc/firmware/focaltech_8725_fw.bin, open failed: No such file or directory [ 28.602669] (6)[661:ueventd]ueventd: firmware: attempted /odm/firmware/focaltech_8725_fw.bin, open failed: No such file or directory [ 28.602686] (6)[661:ueventd]ueventd: firmware: attempted /vendor/firmware/focaltech_8725_fw.bin, open failed: No such file or directory [ 28.602701] (6)[661:ueventd]ueventd: firmware: attempted /firmware/image/focaltech_8725_fw.bin, open failed: No such file or directory [ 28.602771] (6)[661:ueventd]ueventd: loading /devices/platform/11012000.spi2/spi_master/spi2/spi2.0/firmware/focaltech_8725_fw.bin took 0ms [ 28.603152] (2)[309:irq/135-fts_ts][FTS_TS/E]fts_fw_resume:fts_fw_resume:firmware(focaltech_8725_fw.bin) request fail,ret=-11\x0a

Does the touchscreen work in the android?

**Comment by RhythmConnoisseurYT** [comment]
> > Oh okay. I'm used to adb sideload so I didn't know you could access adb from the base. Anyways, the terminal didn't recognize grep error but when I just did adb shell dmesg, I found similar errors to the ones you previously found in the OP
> > [ 28.602633] (6)[661:ueventd]ueventd: firmware: could not find firmware for focaltech_8725_fw.bin [ 28.602653] (6)[661:ueventd]ueventd: firmware: attempted /etc/firmware/focaltech_8725_fw.bin, open failed: No such file or directory [ 28.602669] (6)[661:ueventd]ueventd: firmware: attempted /odm/firmware/focaltech_8725_fw.bin, open failed: No such file or directory [ 28.602686] (6)[661:ueventd]ueventd: firmware: attempted /vendor/firmware/focaltech_8725_fw.bin, open failed: No such file or directory [ 28.602701] (6)[661:ueventd]ueventd: firmware: attempted /firmware/image/focaltech_8725_fw.bin, open failed: No such file or directory [ 28.602771] (6)[661:ueventd]ueventd: loading /devices/platform/11012000.spi2/spi_master/spi2/spi2.0/firmware/focaltech_8725_fw.bin took 0ms [ 28.603152] (2)[309:irq/135-fts_ts][FTS_TS/E]fts_fw_resume:fts_fw_resume:firmware(focaltech_8725_fw.bin) request fail,ret=-11\x0a
> 
> Does the touchscreen work in the android?

Yeah it was working without issue before and after unlocking the oem on MIUI.

**Comment by AntarcticShaurant** [comment]
Posted the build, sorry it took this much, but i was a bit busy

**Comment by RhythmConnoisseurYT** [comment]
> Posted the build, sorry it took this much, but i was a bit busy

No problem at all.
This build works! :)
Thank you so much. I was stuck in fastboot purgatory for a while there.

**Comment by AntarcticShaurant** [comment]
Glad to hear that!
Then you may keep using it until the next build.

I'll close this issue as soon as I'll see that it works for @skvorecoo as well.

**Comment by skvorecoo** [comment]
everything works as it should. thank you
