### ISSUE TITLE
ADB Sideload Issue? "Devices on super may not mount until rebooting."

### ISSUE THREAD

**Issue by RhythmConnoisseurYT** [Xiaomi-fire-unofficial-development/twrp_device_xiaomi_fire#21]
**Describe the bug**
Hello, sorry to bother, but I encountered an issue with the adb sideload feature while using both the original version that fixed the touchscreen issue and the newest version. When I try to sideload a rom, I get the message:
"Devices on super may not mount until rebooting recovery. To flash additional zips, please reboot recovery to switch to the updated slot." on TWRP and then in the terminal,
[ C:\platform-tools>adb sideload lineage-21.0-20240318-UNOFFICIAL-cupid.zip
* daemon not running; starting now at tcp:5037
* daemon started successfully
Total xfer: 0.00x ] 

 I'm not sure if this is because of TWRP or the rom being potentially incompatible, or if there's a workaround on my end, because I tried switching slots before, both in TWRP  and through fastboot and the same message keeps coming up. Thanks in advance.

**Comment by AntarcticShaurant** [comment]
Well, I see the rom is for cupid (Xiaomi 12), while this recovery is for fire (Xiaomi Redmi 12), and since i guess you managed to flash TWRP on your device i guess you have fire, so the rom is the issue here.

**Comment by AntarcticShaurant** [comment]
Mind sharing some logs just in case, i'm a bit curious as to why it doesn't transfer anything instead of flashing and bootlooping.

**Comment by RhythmConnoisseurYT** [comment]
Yeah, I kind of was expecting that to be the case, but couldn't find any custom fire roms to test with. Anyways, how do I access the logs?

**Comment by AntarcticShaurant** [comment]
In the recovery, just go to advanced > copy log, and select both logcat and kernel logs

> version that fixed the touchscreen issue

Oh by the way, that version was just a test, twrp is now official, so just download it from twrp.me

**Comment by RhythmConnoisseurYT** [comment]
Thank you for talking me through this. I flashed the official twrp and then just started flashing the official miui rom and it worked so I guess it was just due to issues with it being cupid since this is fire. Sucks there's no custom roms for this version but it happens. I'll close it then.
