### ISSUE TITLE
porting orangefox

### ISSUE THREAD

**Issue by mahdi-salimi05** [Xiaomi-fire-unofficial-development/twrp_device_xiaomi_fire#23]
i've done the orange fox building using [this source ](https://github.com/mahdi-salimi05/twrp_device_xiaomi_fire/tree/fox_12.1). you can grep my source code to your repository 

here is the built of orange fox with that source code which i've ported:

https://github.com/mahdi-salimi05/Action-OFRP-Builder

**Comment by AntarcticShaurant** [comment]
This is TWRP, why would i need your OrangeFox port?

**Comment by mahdi-salimi05** [comment]
why you are using miui kernel? hyper os 1.0.4.0 update have newer kernel! if you update the kernel to the latest version, it couldn't break miui; because redmi 12 have android 12 kernel and it is compatible to android 12+
